version: "3.8"

services:
  webapp:
    image: php:8.1
    command: php -S 0.0.0.0:8080 -t public cli-fc.php
    init: true
    environment:
      - PHP_CLI_SERVER_WORKERS=4
    ports:
      - "8080:8080"
    volumes:
      - .:/var/www/webapp
    working_dir: /var/www/webapp
